### PR TITLE
Allow placeholders to be used in imports

### PR DESCRIPTION
**Pull request by sascha-egerer**
Enable the use of placeholders for import statements.

Example:

```
imports:
  - { resource: 'context/%env(APPLICATION_CONTEXT)%/*.yaml', type: glob }
```

### CODE REVIEW

**Comment by sascha-egerer** [comment]
The failed build is not related to this change.

**Comment by helhum** [comment]
Thanks for the PR. Unfortunately I cannot merge such a change, because it has broader implications.

The idea with placeholders and caching is, that it is possible to not only write static caches, with all values resolved, but also dynamic caches, where values are still pulled from runtime values.
Most apparently not the value for `%env(FOO)%` is written to the cache when it is created, but PHP code like `getenv('FOO')`.

This won't work for placeholders in resources, because imports are resolved beforehand and the cache is written based on the complete configuration.

To support dynamic placeholders in imports, the whole import resolving would need to be rewritten and I doubt this would be worth the effort.

Other than these implications, I'm still not sure and therefore not convinced, that such change would solve issues that otherwise would not be solvable but for sure would introduce additional complexity in understanding which configuration files are actually loaded when (while being fairly complex already depending on how your config files are structured).

I'll therefore close this PR now, but would still be interested in the use case you have to introduce such change and why you would not like to solve your use case otherwise.

**Comment by sascha-egerer** [comment]
Hi @helhum,

the use case is pretty simple. I would like to overwrite configurations for specific contexts and have those configuration managed under version control.

So I don't understand your objections in detail as I'm using the patched version and it work's pretty like i expect it to work. Maybe would be helpful to have a quick call on that.

**Comment by sascha-egerer** [comment]
Just had a call with @helhum about that topic. First of all thank you @helhum for your time.

My initial use case was to load a stage specific configuration which is, in my case, based on the application context.
@helhum has suggested a solution that I had not thought of. The problem can be solved by creating a `override.settings.yaml` (that is the default name used by `helhum/typo3-config-handling`) which then has the environment specific include.
So on the system with the context `Production/Live` the file `override.settings.yaml` must contain this import.
```
imports:
  - { resource: 'context/Production/Live/*.yaml', type: glob }
 ```

In `helhum/typo3-config-handling` it is possible to adjust the path to the `override.settings.yaml` to be outside of the release path. So the file can be persisted on the environment itself without any requirement to the deployment.

This solution does work without doing any changes to the config handling and does resolve my requirement.

**Pull request closed without merging**
